### ISSUE TITLE
SonsaYT

### ISSUE THREAD

**Issue by PotatoeTrainYT** [RushToEasy/treehousemc-xXNiceYTXx#4]
SonsaYT is the fakest of them all.
Reasons:

- [x] Fake
- [x] More fake than BajanVlogs (REALLY HARD TO DO)
- [ ] Has friends
- [ ] Can code
- [x] Scammer
- [ ] Makes good plugins
- [x] Calls people fake who exposed him
- [x] Jealous he can't make a server with players
- [x] Banned on YouTube for scamming
- [x] Advertising prick

Comment to help add more to this list

**Comment by RushToEasy** [comment]
Nope
